messages:
  not_clan: "&cТы не состоишь в клане"
  subcommand_not_found: "&6Подкоманда не найдена!"
  joined_clan: "&aТы вступил в клан &6&l{clanName}"

  player_added: "&aИгрок&c {targetUserName} &aдобавлен в клан"
  player_already_in_clan: "&cИгрок уже состоит в клане"
  player_not_in_clan: "&cИгрок не состоит в вашем клане клане"
  player_kicked_cause: "&aИгрок&c {targetUserName} &aбыл кикнут игроком &c{userName} &aпо причине: &6{cause}"
  player_kicked: "&aИгрок&c {targetUserName} &aбыл кикнут игроком &c{userName}"
  player_already_has_invite: "&aИгрок уже имеет приглашеине"
  player_not_respond_invitation: "&c{targetUserName} &aне ответил на приглашение"
  player_invites_to_clan: "&aИгрок &c{userName} &aприглашает тебя в клан &6&l{clanName}"
  player_accepted_invitation: "&aИгрок &c{targetUserName} &aпринял приглашение"

  pvp_disabled: "&aПвп между товарищами было отключено"
  pvp_enabled: "&aПвп между товарищами было включено"

  invitation_sent_to_player: "&aПриглашение отправлено игроку &c{targetUserName}"

  permission_betrayed: "&aЛидерство перенадо игроку &c{targetUserName}"

  you_already_in_clan: "&cТы уже состоишь в клане"
  you_kicked_from_clan_cause: "&aТы был кикнут из клана игроком &c{userName} &aпо причине: &6{cause}"
  you_kicked_from_clan: "&aТы был кикнут из клана игроком &c{userName}"
  you_dont_have_invitations: "&cУ тебя нет активных пришлашений"
  you_dont_have_money: "&cНа балансе недостаточно средств"

  lack_of_rights: "&cУ тебя недостаточно прав на использование данной команды"

  clan_created: "&aКлан &6&l{clanName} &aуспешно создан"
  clan_deleted: "&aКлан успешно удалён"
  clan_renamed: "&aНазвание клана изменено на &6&l{newClanName}"
  clan_name_failed: "&cНазвание клана уже уществует или указано неправильно"
  clan_home_not_found: "&cУ клана не создан клановый хом"
  clan_home_created: "&aХом клана обновлен"
  clan_leave: "&aИгрок &c{userName} &aпокинул клан"
  clan_leave_failed: "&cЛидер клана не может покинуть клан"
  clan_up_level_failed: "&cВ казне недостаточно средсв"
  clan_up_level: "&aУровень клана был повышен"
  clan_max_level: "&cУровень клана повышен до максимального уровня"
  clan_pay: "&aИгрок &c{userName} &aвнёс в казну &6{amount}$"
  clan_pay_failed: "&cКазна не может вместить такую сумму"
  clan_take: "&aИгрок &c{userName} &aвзял из казны &6{amount}$"
  clan_take_failed: "&cВ казне недостаточно средств"

  zero_cannot_output: "&cСлишком маленькая сумма"

  command_failed: "&cКоманда была введена не правильно"

  group_player_up: "&aГруппа игрока &c{targetUserName} &aбыла повышена до &c{group}"
  group_player_down: "&aГруппа игрока &c{targetUserName} &aбыла понижена до &c{group}"
  group_cannot_be_raised: "&cГруппа игрока уже повышена до максимального уровня"
  group_reduced_to_minimum_level: "&cГруппа игрока уже понижена до минимального уровня"

  no_money: "&cНедостаточно средств"
  not_enough_money: "&cНедостаточно средств клана"

  welcome_message_created: "&aПриветственное сообщение было обновлено"
  welcome_failed: "&cПриветственное сообщение не было указано"

  command_help: "
  &c/clan &a- Открыть меню клана \n
  &c/cc &a - Клановый чат \n
  &c/clan create <name> &a- Создать клан \n
  &c/clan add <nick> &a- Добавить игрока в клан \n
  &c/clan kick <nick> &a- Кикнуть игрока из клана \n
  &c/clan delete &a- Удалить клан \n
  &c/clan leave &a- Покинуть клан \n
  &c/clan setleader <nikc> &a- Передать лидерство \n
  &c/clan sethome &a- Установить хом клана \n
  &c/clan home &a- Телепортироваться на клан хом \n
  &c/clan levelup &a- Повысить уровень клана \n
  &c/clan pay <sum> &a- Положить деньги в казну клана \n
  &c/clan take <sum> &a- Снять деньги с казны клана \n
  &c/clan pvp <on/off> &a- Вкл/Выкл пвп между кланом \n
  &c/clan rename <name> &a- Переименовать клан \n
  &c/clan rank <name> <up/down> &a- Повысить ранг участника клана \n
  &c/clan welcome <message> &a- Обновить приветственное сообщение"


color_settings:
  menu:
    menu_color: "&a"
    name_color: "&c"
    time_color: "&6"
    clan_name_color: "&6&l"
    clan_rep_color: "&6"
    clan_level_color: "&c"
    clan_amount_kills_color: "&c"
    clan_amount_player_color: "&6"
    clan_balance_color: "&6"
    player_group_color: "&c"
    navigation_color: "&e"
    online_color: "&2"
    offline_color: "&c"


clan_settings:
# Длинна имени клана
  clan_name_length: 3

#  Нужный баланс клана для повышения уровня
  balance_to_level_up_one: 100
  balance_to_level_up_two: 150
  balance_to_level_up_three: 200

# Максимальный баланс для каждого уровня клана
  max_balance_level_zero: 500
  max_balance_level_one: 1000
  max_balance_level_two: 1050
  max_balance_level_three: 1100
  max_amount_players: 100
  max_clan_level: 3

# Цена /rename
  price_rename: 100
  price_create_clan: 0

# Права на использование команды.
# 0 Игрок
# 1 Доверенный
# 2 Создатель
  permission_for_kick: 1
  permission_for_add: 1
  permission_for_sethome: 1
  permission_for_up_rank: 2
  permission_for_set_welcome_message: 2
  permission_for_rename: 2
  permission_for_delete: 2
  permission_for_set_pvp: 2
  permission_for_up_level: 2
  permission_for_take: 2

# Кол-во репутации за количество убийств (стоит int)
  amount_reputation_for_kills: 1
# За каждый десятый килл + репутация
  reputation_for_amount_kills: 10