name: SystemClans
version: '${project.version}'
main: org.dokat.systemclans.SystemClans
api-version: 1.18
authors: [ Dokat ]
depends: [Vault, EssentialsX]
commands:
  accept:
  clanchat:
    aliases: [cc]
  clan:
    aliases: [c]
    subcommands:
      create:
      delete:
      add:
      kick:
      leave:
      sethome:
      home:
      welcome:
      setleader:
      levelup:
      pay:
      take:
      pvp:
      rename:
      rank:
      help: