name: SystemClans
version: '${project.version}'
main: org.dokat.systemclans.SystemClans
api-version: 1.18
authors: [ Dokat ]
depends: [Vault, EssentialsX]
commands:
  b:
  accept:
  clanchat:
    aliases: [cc]
  clan:
    aliases: [c]
    subcommands:
      create:
      add:
      remove: