name: SystemClans
version: '${project.version}'
main: org.dokat.systemclans.SystemClans
api-version: 1.16
authors: [ Dokat ]
depends: [Vault, EssentialsX, CombatLib]
commands:
  t:
  accept:
  clanchat:
    aliases: [cc]
  clan:
    aliases: [c]